#!/bin/bash
# Rustscape - Run Server Stack
#
# This script starts the game server with its supporting services.
# Usage: ./scripts/run.sh [command]
#
# Commands:
#   start     - Start the server stack (default)
#   stop      - Stop the server stack
#   restart   - Restart the server stack
#   logs      - View logs from all services
#   status    - Show status of all services
#   build     - Rebuild the server images
#   clean     - Stop and remove all containers and volumes
#   dev       - Start with dev tools (pgAdmin, Redis Commander)
#   init      - Initialize/regenerate .env file

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} $1"
}

print_banner() {
    echo ""
    echo "╔══════════════════════════════════════════════╗"
    echo "║           Rustscape Server Stack             ║"
    echo "╚══════════════════════════════════════════════╝"
    echo ""
}

# Generate a secure random string
generate_secret() {
    local length="${1:-64}"
    # Use /dev/urandom for cryptographically secure random bytes
    if command -v openssl &> /dev/null; then
        openssl rand -base64 "$length" | tr -d '\n/+=' | head -c "$length"
    elif [ -f /dev/urandom ]; then
        head -c "$length" /dev/urandom | base64 | tr -d '\n/+=' | head -c "$length"
    else
        # Fallback to $RANDOM (less secure, but works everywhere)
        local result=""
        local chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
        for i in $(seq 1 "$length"); do
            result="${result}${chars:RANDOM%${#chars}:1}"
        done
        echo "$result"
    fi
}

# Generate a secure password with special characters
generate_password() {
    local length="${1:-32}"
    if command -v openssl &> /dev/null; then
        openssl rand -base64 "$length" | tr -d '\n' | head -c "$length"
    else
        generate_secret "$length"
    fi
}

# Check if .env file exists and is valid
check_env_file() {
    if [ ! -f "$PROJECT_DIR/.env" ]; then
        return 1
    fi

    # Check if required variables are set
    source "$PROJECT_DIR/.env" 2>/dev/null || return 1

    if [ -z "$POSTGRES_PASSWORD" ] || [ -z "$RUSTSCAPE_JWT_SECRET" ]; then
        return 1
    fi

    return 0
}

# Generate .env file with secure credentials
generate_env_file() {
    local force="${1:-false}"

    if [ -f "$PROJECT_DIR/.env" ] && [ "$force" != "true" ]; then
        log_info ".env file already exists. Use 'init --force' to regenerate."
        return 0
    fi

    log_step "Generating secure credentials..."

    # Generate secure random values
    local postgres_password=$(generate_password 32)
    local redis_password=$(generate_password 32)
    local jwt_secret=$(generate_secret 64)
    local pgadmin_password=$(generate_password 16)

    log_step "Creating .env file..."

    cat > "$PROJECT_DIR/.env" << EOF
# ============================================
# Rustscape Server Configuration
# ============================================
# This file was auto-generated by run.sh
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# WARNING: This file contains sensitive credentials.
# Do NOT commit this file to version control!
# ============================================

# --------------------------------------------
# PostgreSQL Database
# --------------------------------------------
POSTGRES_USER=rustscape
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=rustscape
POSTGRES_PORT=5432
POSTGRES_EXTERNAL_PORT=5433

# --------------------------------------------
# Redis Cache
# --------------------------------------------
REDIS_PASSWORD=${redis_password}
REDIS_PORT=6379
REDIS_EXTERNAL_PORT=6380

# --------------------------------------------
# Rustscape Server
# --------------------------------------------
RUSTSCAPE_DEV_MODE=true
RUSTSCAPE_DEBUG=false

# Database connection (uses values above)
RUSTSCAPE_DATABASE_TYPE=postgres
RUSTSCAPE_DATABASE_HOST=postgres
RUSTSCAPE_DATABASE_PORT=5432
RUSTSCAPE_DATABASE_USER=rustscape
RUSTSCAPE_DATABASE_PASSWORD=${postgres_password}
RUSTSCAPE_DATABASE_NAME=rustscape

# Redis connection
RUSTSCAPE_REDIS_HOST=redis
RUSTSCAPE_REDIS_PORT=6379
RUSTSCAPE_REDIS_PASSWORD=${redis_password}

# JWT Authentication (CRITICAL - keep this secret!)
RUSTSCAPE_JWT_SECRET=${jwt_secret}
RUSTSCAPE_JWT_ACCESS_EXPIRY=86400
RUSTSCAPE_JWT_REFRESH_EXPIRY=604800

# Authentication settings
RUSTSCAPE_AUTH_REGISTRATION_ENABLED=true
RUSTSCAPE_AUTH_MIN_PASSWORD_LENGTH=6
RUSTSCAPE_AUTH_MAX_LOGIN_ATTEMPTS=5
RUSTSCAPE_AUTH_LOCKOUT_DURATION=900
RUSTSCAPE_AUTH_BCRYPT_COST=12

# Server settings
RUSTSCAPE_WORLD_ID=1
RUSTSCAPE_WORLD_NAME=Rustscape
RUSTSCAPE_MAX_PLAYERS=2000

# Logging
RUST_LOG=info,rustscape_server=debug

# --------------------------------------------
# Nginx Web Server
# --------------------------------------------
NGINX_HTTP_PORT=8088
NGINX_HTTPS_PORT=8443

# --------------------------------------------
# Development Tools (optional)
# --------------------------------------------
# pgAdmin
PGADMIN_EMAIL=admin@rustscape.local
PGADMIN_PASSWORD=${pgadmin_password}
PGADMIN_PORT=5050

# Redis Commander
REDIS_COMMANDER_PORT=8081

# --------------------------------------------
# Timezone
# --------------------------------------------
TZ=America/New_York
EOF

    # Secure the file permissions (read/write for owner only)
    chmod 600 "$PROJECT_DIR/.env"

    log_success ".env file created successfully!"
    echo ""
    log_info "Generated credentials:"
    echo "  PostgreSQL Password: ${postgres_password:0:8}... (hidden)"
    echo "  Redis Password:      ${redis_password:0:8}... (hidden)"
    echo "  JWT Secret:          ${jwt_secret:0:8}... (hidden)"
    echo "  pgAdmin Password:    ${pgadmin_password}"
    echo ""
    log_warn "Save these credentials securely! They are stored in .env"
    log_warn "The .env file has been set to mode 600 (owner read/write only)"
}

# Ensure .env exists before starting services
ensure_env() {
    if ! check_env_file; then
        log_warn ".env file missing or incomplete!"
        generate_env_file
    fi

    # Source the .env file
    set -a
    source "$PROJECT_DIR/.env"
    set +a
}

wait_for_postgres() {
    log_info "Waiting for PostgreSQL to be healthy..."
    local retries=0
    local max_retries=30

    while [ $retries -lt $max_retries ]; do
        if docker compose exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
            log_success "PostgreSQL is ready"
            return 0
        fi
        retries=$((retries + 1))
        echo -n "."
        sleep 2
    done
    echo ""
    log_error "PostgreSQL failed to become ready"
    return 1
}

wait_for_redis() {
    log_info "Waiting for Redis to be healthy..."
    local retries=0
    local max_retries=15

    while [ $retries -lt $max_retries ]; do
        if docker compose exec -T redis redis-cli ping >/dev/null 2>&1; then
            log_success "Redis is ready"
            return 0
        fi
        retries=$((retries + 1))
        echo -n "."
        sleep 1
    done
    echo ""
    log_error "Redis failed to become ready"
    return 1
}

start_services() {
    ensure_env

    log_info "Starting Rustscape server stack..."

    # Start infrastructure first (postgres, redis)
    docker compose up -d postgres redis

    # Wait for infrastructure
    wait_for_postgres
    wait_for_redis

    # Start server and nginx
    docker compose up -d server nginx

    log_success "Server stack started!"
    echo ""
    log_info "Services available at:"
    echo "  - Web Client:    http://localhost:${NGINX_HTTP_PORT:-8088}"
    echo "  - WebSocket:     ws://localhost:${NGINX_HTTP_PORT:-8088}/ws (proxied)"
    echo "  - Game TCP:      localhost:43597 (base), localhost:43598 (world 1)"
    echo "  - REST API:      http://localhost:${NGINX_HTTP_PORT:-8088}/api/v1"
    echo "  - Management:    localhost:5556"
    echo "  - PostgreSQL:    localhost:${POSTGRES_EXTERNAL_PORT:-5433}"
    echo "  - Redis:         localhost:${REDIS_EXTERNAL_PORT:-6380}"
    echo ""
    log_info "API Endpoints:"
    echo "  - POST /api/v1/auth/register      - Create new account"
    echo "  - POST /api/v1/auth/login         - Login and get JWT"
    echo "  - POST /api/v1/auth/logout        - Logout"
    echo "  - GET  /api/v1/auth/session       - Check session"
    echo "  - POST /api/v1/auth/refresh       - Refresh JWT token"
    echo ""
}

start_dev() {
    ensure_env

    log_info "Starting Rustscape server stack with dev tools..."

    # Start infrastructure first
    docker compose up -d postgres redis

    # Wait for infrastructure
    wait_for_postgres
    wait_for_redis

    # Start server, nginx, and dev tools
    docker compose --profile dev up -d

    log_success "Server stack with dev tools started!"
    echo ""
    log_info "Services available at:"
    echo "  - Web Client:    http://localhost:${NGINX_HTTP_PORT:-8088}"
    echo "  - WebSocket:     ws://localhost:${NGINX_HTTP_PORT:-8088}/ws (proxied)"
    echo "  - Game TCP:      localhost:43597 (base), localhost:43598 (world 1)"
    echo "  - REST API:      http://localhost:${NGINX_HTTP_PORT:-8088}/api/v1"
    echo "  - Management:    localhost:5556"
    echo "  - PostgreSQL:    localhost:${POSTGRES_EXTERNAL_PORT:-5433}"
    echo "  - Redis:         localhost:${REDIS_EXTERNAL_PORT:-6380}"
    echo ""
    log_info "Dev Tools:"
    echo "  - pgAdmin:         http://localhost:${PGADMIN_PORT:-5050}"
    echo "                     Email: ${PGADMIN_EMAIL:-admin@rustscape.local}"
    echo "                     Password: (see .env file)"
    echo "  - Redis Commander: http://localhost:${REDIS_COMMANDER_PORT:-8081}"
    echo ""
}

stop_services() {
    log_info "Stopping server stack..."
    docker compose --profile dev down
    log_success "Server stack stopped"
}

restart_services() {
    stop_services
    start_services
}

show_logs() {
    docker compose logs -f "$@"
}

show_status() {
    ensure_env
    log_info "Service status:"
    echo ""
    docker compose ps -a
}

build_server() {
    ensure_env
    log_info "Building server images..."
    docker compose build server nginx
    log_success "Build complete"
}

clean_all() {
    log_warn "This will remove all containers and volumes!"
    log_warn "All data (users, players, etc.) will be DELETED!"
    read -p "Are you sure? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        log_info "Stopping and removing containers..."
        docker compose --profile dev down -v
        log_success "Cleanup complete"
    else
        log_info "Cancelled"
    fi
}

init_env() {
    local force="false"
    if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
        force="true"
    fi
    generate_env_file "$force"
}

show_help() {
    echo "Usage: $0 [command] [options]"
    echo ""
    echo "Commands:"
    echo "  start         Start the server stack (default)"
    echo "  stop          Stop the server stack"
    echo "  restart       Restart the server stack"
    echo "  logs [svc]    View logs (optionally for specific service)"
    echo "  status        Show status of all services"
    echo "  build         Rebuild the server images"
    echo "  clean         Stop and remove all containers and volumes"
    echo "  dev           Start with dev tools (pgAdmin, Redis Commander)"
    echo "  init [--force] Initialize/regenerate .env file"
    echo "  help          Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                  # Start the server"
    echo "  $0 dev              # Start with dev tools"
    echo "  $0 logs server      # View server logs only"
    echo "  $0 init --force     # Regenerate .env with new secrets"
    echo ""
}

# Parse command
COMMAND="${1:-start}"
shift 2>/dev/null || true

print_banner

case "$COMMAND" in
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    restart)
        restart_services
        ;;
    logs)
        show_logs "$@"
        ;;
    status)
        show_status
        ;;
    build)
        build_server
        ;;
    clean)
        clean_all
        ;;
    dev)
        start_dev
        ;;
    init)
        init_env "$@"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        log_error "Unknown command: $COMMAND"
        echo ""
        show_help
        exit 1
        ;;
esac
